busybox: bump to 1.20.1
This includes a fix when compiling with a recent glibc, where gcc would
exit, complaining that

loginutils/passwd.c:188:12: error: ‘RLIMIT_FSIZE’ undeclared (first use
in this function)